// This file is generated by Slice Machine. Update with care!

import Image from './Image';
import RichText from './RichText';

export {
	Image,
	RichText,
};

export const components = {
	image: Image,
	rich_text: RichText,
};
